# scipy.sparse

稀疏矩阵

In [29]:
a.sum(1)

array([ 3,  3, 15,  0])

In [2]:
import numpy as np
import scipy.sparse as sp

In [27]:
a = np.array([[1, 0, 2],
              [0, 0, 3],
              [4, 5, 6],
              [0, 0, 0]])

In [4]:
a_csr = sp.csr_matrix(a)
print(a_csr.indptr)
print(a_csr.indices)

[0 2 3 6 6]
[0 2 2 0 1 2]


In [14]:
a_coo = sp.coo_matrix(a_csr)
rowsum = a_coo.sum(1)
print(rowsum)
d_inv_sqrt = np.power(rowsum, -0.5).flatten()

[[ 3]
 [ 3]
 [15]
 [ 0]]


C:\Users\Kevin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in power
  after removing the cwd from sys.path.


In [15]:
d_inv_sqrt

matrix([[0.57735027, 0.57735027, 0.25819889,        inf]])

In [17]:
d_inv_sqrt[np.isinf(d_inv_sqrt.flatten())] = 0 
d_inv_sqrt

matrix([[0.57735027, 0.57735027, 0.25819889, 0.        ]])

In [32]:
a = np.isinf(d_inv_sqrt.flatten())
a

matrix([[False, False, False, False]])

In [18]:
d_mat_inv_sqrt = sp.diags(d_inv_sqrt)

ValueError: Different number of diagonals and offsets.

## coo_matrix

.row  记录array中每个元素的行号

.col  记录array中每个元素的列号 

.data 记录array中每个元素内容

.shape array大小

In [19]:
mx = np.array([[1, 0, 2],
              [0, 0, 3],
              [4, 5, 6],
              [0, 0, 0]])
mx = sp.coo_matrix(a)

In [20]:
coords = np.vstack((mx.row, mx.col)).transpose()
values = mx.data
shape = mx.shape

In [21]:
coords

array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int32)

In [22]:
values

array([1, 2, 3, 4, 5, 6])

In [23]:
shape

(4, 3)

In [30]:
'''
每一行特征/每一行的和
'''
def preprocess_features(features):
    """Row-normalize feature matrix and convert to tuple representation"""
    rowsum = np.array(features.sum(1)) #
    r_inv = np.power(rowsum, -1).flatten()
    r_inv[np.isinf(r_inv)] = 0.
    r_mat_inv = sp.diags(r_inv)
    features = r_mat_inv.dot(features)

In [41]:
correct = [False, False, False, True]
false_index = [u for u,v in enumerate(correct) if v == False]
false_index

[0, 1, 2]

ValueError: only 2 non-keyword arguments accepted

In [45]:
a

1


1


In [48]:
debug = True
if debug:
    print('Y')

Y
